### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by swiftvictor** [vecto-ai/vecto#66]
I was able to use veco without problem last week, but today when I try to import veco and assign a model I get the following error:
import vecto
path_to_vsm = "/Users/Y/Downloads/word_linear_sg_500d"
my_vsm = vecto.model.load_from_dir(path_to_vsm)

module 'vecto' has no attribute 'model'

I looked at the initiation file (__init__.py) and it seems to only load the version: 
from ._version import VERSION
and _version.py only loads the version:
VERSION = "0.1.7"

Thankfully, I am still able to use vsmlib. Is there a technical reason that vsmlib was replaced with vecto?

**Comment by undertherain** [comment]
What was "model" in vsmlib is called "embeddings" in vecto, 
since we added multiple evaluations based on neural nets, it became a bit ambiguous of what "model" can refer to. 

use `from vecto.embeddings import load_from_dir`

as for the reasons for rebranding: we have merged our efforts and codebase with another project, called "embeddings gym" and that was sort of good excuse to  adopt better name which will suite everybody and create new organization on github

**Comment by OXPHOS** [comment]
Hi, I was using `Vecto` with `version==0.2.0` and ran into the same problem.
Could you update your [docs](https://vecto.readthedocs.io/en/docs/tutorial/working_with_vectors.html) accordingly?
Thanks!

**Comment by OXPHOS** [comment]
And I believe `vsm.get_word()` is now `vsm.get_id()` in `version0.2.0`?
